build-everything:
    just build-default
    just build-serde
    just build-arc
    just build-all
build-default:
    cargo build
build-serde:
    cargo build --features "serde"
build-arc:
    cargo build --features "arc"
build-all:
    cargo build --features "all"
