build:
    cargo build
import-all:
    just import-basic-titles
    just import-basic-names
    just import-title-principals
import-basic-titles:
    cargo run --release -- import-basic-titles
import-basic-names:
    cargo run --release -- import-basic-names
import-title-principals:
    cargo run --release -- import-title-principals
